### ISSUE TITLE
Certain assets do not have facet value in `AllEverything`

### ISSUE THREAD

**Issue by Alan19** [Alan19/TwoDee#58]
Way of the Dashing Sword, Faith, Consistent Character, and Way of the Pillar seem to not have their facet counts in the `AllEverything` column. @belathus

**Comment by belathus** [comment]
I realized that this was because you had a blank value for "Unfinished Business" which offset the values a bit. So, I had to make it so that the spreadsheet checked to ensure the value it assigns matches the skill it is assigning it to.

I'll have to update everyone's sheets to account for blank assets. This checking already exists for specialty skills and other similar things.

**Comment by belathus** [comment]
I have done this. Let me know if I've missed anything.
